### ISSUE TITLE
Stats are not updating for live logs

### ISSUE THREAD

**Issue by vsagarv** [anikets95/amagi_assignment#1]
Re Question2:

The problem spec was for stats of a "live" web server log. When you were at our office, I also mentioned that this web server is of a large scale system (say google.com) that is in constant & active use.

The current implementation does a one time, split processing and provides stats on that log snapshot.

**Comment by anikets95** [comment]
Yes to update the snapshot , /initialize is required to be reinvoked. 
I intentionally left it like that because I didn't know if I had permissions to make changes in the master logs.

**Comment by anikets95** [comment]
I have updated the code in https://github.com/anikets95/amagi_assignment/commit/ccaa0aee4a3b891f5d0ec11e8927da264fc79c43
I have added code which can add logs in background once initiated using daemon threads and tailer(which will tail the original log)

**Comment by vsagarv** [comment]
Thanks. Ajith will have a call with you today.
